
const PERSONAS = {
  chen:{name:"Chen Wei",initial:"陈",role:"Peer · locally well-connected",traits:"Relationship-oriented; values reciprocity and discretion.",base:{trust:58,warmth:60,respect:61,openness:60,threat:18}},
  jing:{name:"Li Jing",initial:"李",role:"Peer · internationally trained",traits:"Competence-oriented; directness tolerance is relatively high.",base:{trust:60,warmth:55,respect:66,openness:60,threat:16}},
  zhao:{name:"Professor Zhao",initial:"赵",role:"Senior colleague · broad network",traits:"Warm but busy; notices initiative and social calibration.",base:{trust:54,warmth:56,respect:63,openness:52,threat:20}},
  liu:{name:"Dr. Liu",initial:"刘",role:"Senior colleague · influential",traits:"Generally reasonable; dislikes unnecessary friction.",base:{trust:56,warmth:55,respect:65,openness:56,threat:22}},
  wong:{name:"Ms. Wong",initial:"W",role:"Coordinator · informal gatekeeper",traits:"Low formal rank, high practical power; notices entitlement immediately.",base:{trust:55,warmth:52,respect:57,openness:52,threat:18}},
  alex:{name:"Alex",initial:"A",role:"Junior colleague",traits:"Ambitious; calibrating whether it is safe to contribute unfinished ideas.",base:{trust:58,warmth:57,respect:55,openness:64,threat:24}},
  grace:{name:"Grace Lau",initial:"G",role:"Senior executive",traits:"Low patience for process questions; values judgment and ownership.",base:{trust:52,warmth:45,respect:67,openness:48,threat:28}},
  han:{name:"Dr. Han",initial:"韩",role:"Senior collaborator",traits:"Status-sensitive; values loyalty and credit.",base:{trust:56,warmth:50,respect:66,openness:51,threat:27}},
  rui:{name:"Zhou Rui",initial:"周",role:"Cross-team peer",traits:"Overloaded; becomes defensive when blamed.",base:{trust:56,warmth:53,respect:58,openness:55,threat:24}},
  kevin:{name:"Kevin",initial:"K",role:"Peer",traits:"Eager; underestimates how much relationship capital introductions consume.",base:{trust:58,warmth:58,respect:57,openness:61,threat:18}},
};

const SCENARIOS = [
{level:1,title:"The Dinner Invitation",skill:"Refusal without relational rejection",people:["chen"],
context:"You have joined a new team in Shenzhen. Chen Wei, a peer you have worked with twice, invites you to dinner after work. You are tired and genuinely want to go home. You also expect to depend on Chen for local knowledge over the next few months.",
speaker:"chen",quote:"A few of us are going for dinner nearby. Come with us?",
goals:["Protect your evening","Keep the relationship warm","Signal that you value the invitation","Avoid creating a future obligation","Sound natural, not performative"],
follow:"The next morning Chen sends you a useful contact and says: “This person may be able to help with your project.” What do you reply?",
lesson:"Refusing the request and refusing the relationship are not the same act.",
memory:{warm:"Chen remembers that you declined without closing the relationship.",neutral:"Chen files you as task-focused but reliable.",cold:"Chen becomes less likely to make optional invitations."},
delayed:{warm:"Three scenarios later, Chen volunteers context about an unwritten process before you even ask.",neutral:"Chen helps when asked, but rarely anticipates what you need.",cold:"Chen keeps future help correct, narrow and transactional."}},
{level:1,title:"The Small Favor",skill:"Reciprocity and relational memory",people:["jing"],
context:"Li Jing helped you navigate an internal approval last week. Today she asks whether you can review two slides before 4pm. You have time, but it interrupts focused work.",
speaker:"jing",quote:"Could you take a quick look? You were very good at spotting the issue last time.",
goals:["Protect focus time","Acknowledge the earlier favor","Help without becoming permanently available","Maintain peer equality","Set a realistic boundary"],
follow:"Later she asks, “Can I send you one more version tonight?” What do you say?",
lesson:"People often remember whether help felt reciprocal, not only whether it happened.",
memory:{warm:"Jing experiences the exchange as reciprocal rather than transactional.",neutral:"Jing gets the help, but the relational signal stays neutral.",cold:"Jing notices an imbalance between the help she gave and received."},
delayed:{warm:"Jing later recommends you for a small opportunity without being asked.",neutral:"Jing continues to cooperate normally.",cold:"Jing becomes slower to spend discretionary effort on your requests."}},
{level:1,title:"The Public Correction",skill:"Accuracy with face protection",people:["jing","chen"],
context:"In a small meeting, a colleague gives a number that you know is wrong. The error matters, but it can be corrected without stopping the meeting.",
speaker:"jing",quote:"The adoption rate is already above 70%.",
goals:["Keep the factual record accurate","Avoid embarrassing the speaker","Preserve your own credibility","Keep the meeting moving","Make future collaboration easy"],
follow:"After the meeting, your colleague messages: “Thanks for catching that. Where did your number come from?” What do you send?",
lesson:"A correction can improve today's content while quietly damaging tomorrow's information flow.",
memory:{warm:"The correction lands on the number, not on the person.",neutral:"Your competence is clear; the colleague is slightly more cautious.",cold:"The colleague becomes reluctant to share unfinished work around you."},
delayed:{warm:"You start receiving earlier drafts because people expect useful, non-humiliating correction.",neutral:"People share when needed, not before.",cold:"You increasingly see polished work only after decisions are hard to change."}},
{level:1,title:"“Let’s Have Tea Sometime”",skill:"Reading relational bids",people:["zhao"],
context:"A senior colleague you barely know ends a conversation with a vague invitation. You are unsure whether it is literal politeness or a genuine opening.",
speaker:"zhao",quote:"We should have tea sometime. There are a few people I think you should meet.",
goals:["Avoid overcommitting","Recognize a possible relationship opening","Show initiative without chasing","Respect seniority","Clarify the next step"],
follow:"A week passes and Zhao has not contacted you. Do you follow up? Write the message you would send, or explain why you would not.",
lesson:"Some invitations are simultaneously polite language and real relational openings.",
memory:{warm:"Zhao registers genuine interest without feeling pursued.",neutral:"The door stays open, but no momentum is created.",cold:"Zhao assumes the invitation was not especially important to you."},
delayed:{warm:"Zhao later includes you in a small, useful introduction.",neutral:"Nothing negative happens, but the relationship stays dormant.",cold:"A potential introduction simply never occurs."}},
{level:2,title:"The Weak Deck",skill:"Feedback, competence and dignity",people:["jing"],
context:"A colleague sends you a presentation for tomorrow's executive meeting. The structure is weak and several claims are unsupported. You need major changes.",
speaker:"jing",quote:"Can you tell me if this is ready for tomorrow?",
goals:["Improve the deck materially","Protect her confidence","Be honest about the gap","Avoid doing her work for her","Make her more likely to ask early next time"],
follow:"She replies: “I thought the story was already quite clear. Which part do you think is the biggest problem?” Respond.",
lesson:"Good feedback improves today's output and protects tomorrow's information flow.",
memory:{warm:"She hears a problem with the deck, not a verdict on her competence.",neutral:"She understands the gap but becomes more careful around you.",cold:"She fixes the deck and stops showing you early drafts."},
delayed:{warm:"You become a trusted early reviewer.",neutral:"You remain a useful late-stage reviewer.",cold:"Problems reach you later, when they are more expensive to fix."}},
{level:2,title:"The Late Dependency",skill:"Pressure without blame",people:["rui"],
context:"Your project depends on data from another team. They are three days late. Your own deadline is now at risk, and you need movement today.",
speaker:"rui",quote:"Sorry, we’re still checking a few things. Maybe tomorrow.",
goals:["Get the data quickly","Create urgency","Avoid triggering defensiveness","Protect the cross-team relationship","Leave a clear record"],
follow:"Rui says: “We can give you the raw version now, but no guarantee on quality.” What do you do?",
lesson:"Urgency can be communicated as shared risk rather than personal accusation.",
memory:{warm:"Rui experiences pressure, but also shared problem-solving.",neutral:"Rui moves, but treats the interaction as escalation.",cold:"Rui becomes procedurally defensive."},
delayed:{warm:"Rui flags future delays early.",neutral:"Rui communicates on the formal timeline.",cold:"Rui stops volunteering warning signals before deadlines."}},
{level:2,title:"The Extra Assignment",skill:"Saying no upward",people:["liu"],
context:"A senior colleague asks you to join a task force. It is prestigious but not useful for your current goals. You already have too much work.",
speaker:"liu",quote:"It would be great to have you on this. You’d add a lot.",
goals:["Decline the workload","Preserve the senior relationship","Avoid sounding ungrateful","Signal what you can contribute instead","Prevent repeated asks"],
follow:"Liu replies: “Even just the first two meetings would help.” Respond.",
lesson:"A good refusal tells the other person what remains available, not only what is unavailable.",
memory:{warm:"Liu sees a boundary and a cooperative person at the same time.",neutral:"The refusal works, but the relationship gains nothing.",cold:"Liu stops thinking of you for optional opportunities."},
delayed:{warm:"Liu later brings you a better-fitting opportunity.",neutral:"Liu treats future asks normally.",cold:"Your name falls out of Liu's discretionary opportunity set."}},
{level:2,title:"The Complaint About the Boss",skill:"Trust without entanglement",people:["chen"],
context:"A colleague privately complains that your shared boss is making poor decisions and asks what you really think. You partially agree, but do not want to become part of factional politics.",
speaker:"chen",quote:"Honestly, do you also think he has no idea what he’s doing?",
goals:["Stay politically safe","Keep Chen’s trust","Avoid lying","Do not become a quoted source","Understand what Chen actually needs"],
follow:"Chen says: “Don’t worry, I won’t repeat it.” What do you say next?",
lesson:"Sometimes the explicit question is about the boss; the hidden question is whether the speaker can trust you.",
memory:{warm:"Chen feels heard without receiving a portable quote.",neutral:"Chen sees you as politically careful.",cold:"Chen stops bringing candid information to you."},
delayed:{warm:"Chen later gives you early warning about a sensitive decision.",neutral:"Chen shares public information only.",cold:"You become safer politically but poorer informationally."}},
{level:3,title:"The Vague Executive Request",skill:"Clarifying upward without sounding resistant",people:["grace"],
context:"A senior executive asks for “something strategic” by Friday. The request is vague, the stakes are high, and asking too many questions could look like you need hand-holding.",
speaker:"grace",quote:"Can you put together something strategic on how we should approach this?",
goals:["Clarify the deliverable","Signal ownership","Avoid rework","Respect executive time","Demonstrate judgment"],
follow:"Grace replies: “Yes, but keep it to five slides and make sure there is a recommendation.” What do you send back?",
lesson:"Clarification is strongest when framed as judgment: propose an interpretation, then invite correction.",
memory:{warm:"Grace sees you as someone who reduces ambiguity rather than exporting it upward.",neutral:"You get clarity, but appear more instruction-dependent.",cold:"Grace wonders whether you can operate independently."},
delayed:{warm:"Grace gives you a less-defined problem next time — a signal of trust.",neutral:"Grace continues to define tasks tightly.",cold:"Grace routes ambiguous work elsewhere."}},
{level:3,title:"The Junior’s Bad Idea",skill:"Correcting down without shrinking the room",people:["alex"],
context:"A junior colleague proposes an idea in front of the team. You think it will not work. You can explain why in 30 seconds.",
speaker:"alex",quote:"What if we skip the validation step and just test it live?",
goals:["Prevent a bad decision","Keep Alex contributing ideas","Show technical judgment","Maintain psychological safety","Teach, not just reject"],
follow:"Afterward Alex says: “I guess that was a stupid idea.” What do you say?",
lesson:"Your response teaches the whole room what happens to people who offer unfinished ideas.",
memory:{warm:"Alex learns why the idea fails without learning that speaking is dangerous.",neutral:"Alex becomes more cautious.",cold:"Alex learns to bring only polished, low-risk ideas around you."},
delayed:{warm:"Alex later surfaces a real problem early.",neutral:"Alex waits until he has a solution before speaking.",cold:"You discover problems later because juniors pre-filter what reaches you."}},
{level:3,title:"The Credit Problem",skill:"Claiming contribution without humiliating a senior",people:["han"],
context:"A senior colleague presents a project to leadership and describes an idea as if it emerged from the team. You originated the framework and did most of the work.",
speaker:"han",quote:"We developed a new three-part framework…",
goals:["Protect your contribution","Avoid a public status contest","Preserve the relationship","Ensure leaders know your role","Choose the right timing"],
follow:"After the meeting Dr. Han says: “That went well.” What do you say?",
lesson:"Not every correction belongs in the room where the loss occurred. Timing can preserve credit and relationship.",
memory:{warm:"Your ownership becomes clearer without forcing a public loss of face.",neutral:"Your contribution is visible, but the relationship cools.",cold:"The interaction turns into a status contest."},
delayed:{warm:"Han becomes more explicit about credit allocation next time.",neutral:"You monitor attribution more carefully.",cold:"Future collaboration becomes defensive and politically expensive."}},
{level:3,title:"The Informal Gatekeeper",skill:"Respecting power that has no title",people:["wong"],
context:"You need an exception processed quickly. The administrative coordinator has no formal authority over you, but she controls the workflow and knows everyone.",
speaker:"wong",quote:"Normally this takes two weeks. I can’t promise anything.",
goals:["Get help quickly","Avoid entitlement","Recognize her informal power","Make the request easy to help with","Build a future relationship"],
follow:"Ms. Wong says: “Send me the documents now. I’ll see what I can do.” What do you reply?",
lesson:"Formal hierarchy and practical power are not the same map.",
memory:{warm:"Wong chooses to spend discretionary effort on your problem.",neutral:"Wong handles the request correctly.",cold:"Wong follows the standard timeline exactly."},
delayed:{warm:"Wong later warns you before an administrative deadline.",neutral:"Wong remains correct and neutral.",cold:"You learn about process problems only through formal channels."}},
{level:4,title:"The Introduction You Don’t Want to Make",skill:"Network stewardship",people:["kevin","zhao"],
context:"A colleague asks you to introduce him to a senior person you know. You are not confident enough in his work to spend relationship capital on the introduction.",
speaker:"kevin",quote:"Could you introduce me to Professor Zhao? I think he’d really like this project.",
goals:["Protect your senior relationship","Avoid humiliating Kevin","Stay honest","Offer a path forward","Avoid becoming a permanent broker"],
follow:"Kevin says: “I don’t need an endorsement — just put us in touch.” Respond.",
lesson:"An introduction spends trust from two relationships at once.",
memory:{warm:"Kevin understands that you are protecting the quality of the introduction, not hoarding access.",neutral:"Your network stays safe; Kevin feels blocked.",cold:"Kevin interprets the refusal as status-guarding."},
delayed:{warm:"Kevin later returns with a stronger ask and asks for your judgment first.",neutral:"Kevin seeks other routes.",cold:"Kevin casually tells peers that you are difficult to get help from."}},
{level:4,title:"The Resource Fight",skill:"Negotiating scarce resources across teams",people:["rui","grace"],
context:"Two teams need the same analyst for the next month. You have a strong business case, but the other team has a closer relationship with the analyst’s manager.",
speaker:"rui",quote:"We’ve already planned around having her for the month.",
goals:["Secure enough analyst time","Avoid zero-sum hostility","Protect your project deadline","Preserve future cooperation","Understand the other side’s hidden constraints"],
follow:"The manager offers you 40% of the analyst’s time. You believe you need 60%. What do you say?",
lesson:"In networks, winning the allocation and losing the coalition can be a bad trade.",
memory:{warm:"You create a workable split without converting the relationship into a zero-sum game.",neutral:"You secure resources, but the other team becomes more competitive.",cold:"You win this month and lose informal cooperation for the next six."},
delayed:{warm:"The other team later trades a scarce resource with you voluntarily.",neutral:"Future negotiations start from guarded positions.",cold:"Every future resource decision requires formal escalation."}},
{level:4,title:"The Group Dinner",skill:"Reading social investment",people:["grace","liu","alex","chen"],
context:"At a team dinner, your boss, a respected senior colleague, two peers and a new junior are present. Seating and conversation are informal, but people notice who invests attention where.",
speaker:"chen",quote:"You arrive late. There is one seat beside your boss and one beside the new junior.",
goals:["Use the dinner naturally","Strengthen important relationships","Avoid looking transactional","Include lower-power people","Learn something you would not hear in meetings"],
follow:"Halfway through dinner your boss begins a long conversation with someone else. What do you do with your attention?",
lesson:"People notice not only what you say, but whom you choose when no rule tells you whom to choose.",
memory:{warm:"Your attention signals broad relational investment rather than obvious upward networking.",neutral:"You maximize access to power but look somewhat transactional.",cold:"Several people remember that you were socially present but relationally absent."},
delayed:{warm:"A junior later brings you useful information because you felt approachable.",neutral:"Your network remains top-heavy.",cold:"Lower-power people stop treating you as an informal destination for information."}},
{level:4,title:"The Friend in the Project",skill:"Guanxi, merit and graceful boundaries",people:["chen"],
context:"A trusted colleague asks whether his former classmate can join your project. The person is qualified, but not the strongest available candidate.",
speaker:"chen",quote:"He’s very reliable. Could you at least give him a chance?",
goals:["Protect project quality","Respect the colleague’s relational stake","Avoid favoritism","Keep the door open fairly","Protect your reputation"],
follow:"Your colleague says: “I’m not asking you to hire him — just interview him.” What do you do?",
lesson:"Relationship obligations can be acknowledged without pretending they override standards.",
memory:{warm:"The colleague feels that the relationship was recognized while standards remained visible.",neutral:"You preserve merit but create relational disappointment.",cold:"The colleague concludes that your model of fairness leaves no room for relational consideration."},
delayed:{warm:"The colleague remains willing to stake reputation on future recommendations.",neutral:"Future recommendations become more cautious.",cold:"The colleague stops connecting you to people in his network."}},
{level:5,title:"The Questionable Shortcut",skill:"Integrity under relational pressure",people:["grace","alex"],
context:"Your boss asks you to skip a control step to hit a deadline. It is not illegal, but it creates a risk you would normally reject.",
speaker:"grace",quote:"We all know the control is conservative. Just do it this once.",
goals:["Protect professional integrity","Avoid humiliating the boss","Keep the project moving","Create a defensible record","Avoid becoming the permanent person who says no"],
follow:"The boss replies: “Fine. What can you give me by tomorrow instead?” Respond.",
lesson:"A one-time exception is also a signal about what can be asked of you next time.",
memory:{warm:"You resist the shortcut while remaining useful to the underlying objective.",neutral:"You protect the standard but are categorized as rigid under pressure.",cold:"The conflict becomes about loyalty rather than risk."},
delayed:{warm:"The boss later asks for your risk judgment before deciding.",neutral:"The boss consults you after decisions are mostly formed.",cold:"The boss routes time-sensitive work around you."}},
{level:5,title:"Two Seniors, One Disagreement",skill:"Surviving triangulation",people:["grace","han"],
context:"Two senior leaders disagree privately. Each separately asks for your view. You have a real opinion, but either side could quote you later.",
speaker:"grace",quote:"Between us, you see the problem with his plan too, right?",
goals:["Give useful judgment","Avoid becoming ammunition","Protect both senior relationships","Preserve your credibility","Keep strategic independence"],
follow:"Dr. Han later asks: “Grace spoke to you, didn’t she?” What do you say?",
lesson:"When powerful people are in conflict, being useful is different from being recruitable.",
memory:{warm:"Both leaders see you as thoughtful and discreet rather than recruitable.",neutral:"One side trusts your judgment; the other becomes cautious.",cold:"You become part of the conflict rather than an adviser to it."},
delayed:{warm:"Both sides continue to seek your judgment privately.",neutral:"Your access becomes asymmetric.",cold:"Your statements are interpreted through factional alignment."}},
{level:5,title:"The Underperforming Colleague",skill:"Compassion, standards and team fairness",people:["alex","liu"],
context:"A colleague’s performance has dropped because of a difficult family situation. You know the reason. The rest of the team only sees missed deadlines and is becoming resentful.",
speaker:"alex",quote:"Why are we always covering for him?",
goals:["Protect private information","Maintain team fairness","Support the colleague","Keep standards credible","Prevent resentment from spreading"],
follow:"The manager asks you privately: “Do you think we should reduce his responsibilities for a month?” What do you say?",
lesson:"Confidentiality can protect one person while unintentionally making the system feel unfair to everyone else.",
memory:{warm:"The team gets a fairer operating structure without exposing private details.",neutral:"The workload problem is managed, but trust remains uneven.",cold:"Either the vulnerable colleague or the team feels sacrificed for the other."},
delayed:{warm:"The team sees flexibility as structured rather than arbitrary.",neutral:"People tolerate the arrangement but continue to watch it.",cold:"The episode becomes evidence that standards depend on relationships."}},
{level:5,title:"The Reorganization",skill:"Loyalty, visibility and long memory",people:["grace","han","liu"],
context:"A reorganization may create a major new role. A senior ally who supported you earlier asks you to publicly back his proposal. You agree with about 70% of it. Another leader you respect has a competing plan.",
speaker:"han",quote:"I need people I trust to stand behind this. Can I count on you in the meeting?",
goals:["Protect strategic independence","Acknowledge past support","Avoid public disloyalty","Stay credible with both camps","Maximize long-term influence"],
follow:"In the meeting, the chair asks you directly: “Matthias, which proposal do you support?” What do you say?",
lesson:"High-level social decisions build a reputation for loyalty, independence and judgment — not merely a record of who won one meeting.",
memory:{warm:"You preserve gratitude and independence, though neither camp gets total ownership of you.",neutral:"Your position is clear and one relationship takes a visible hit.",cold:"Short-term alignment costs long-term credibility with the other side or with observers."},
delayed:{warm:"You become known as independent but not disloyal.",neutral:"You are increasingly associated with one camp.",cold:"Future opportunities become contingent on factional outcomes."}}
];
